name: Build macOS App
on: [push]

jobs:
  build-mac:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-file: '3.11'

      - name: Install dependencies
        run: |
          pip install pyinstaller customtkinter flask websockets

      - name: Build with PyInstaller
        run: |
          pyinstaller --noconfirm --onedir --windowed --add-data "static:static" main.py

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: WindyBridge-macOS
          path: dist/*.app
