name: Build macOS App
on: [push]

jobs:
  build-mac:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' # Il est plus sûr d'utiliser une version stable comme la 3.11 ou 3.12 pour PyInstaller

      - name: Install dependencies
        run: |
          pip install pyinstaller customtkinter flask websockets

      - name: Build with PyInstaller
        run: |
          pyinstaller --noconfirm --onedir --windowed --add-data "server/static:static" server/server_interface_travaillee.py

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: WindyBridge-macOS
          path: dist/*.app
